### ISSUE TITLE
Odd Behavior

### ISSUE THREAD

**Issue by kbysfm** [dlnetworks/twittercast#10]
I migrated our server over to DNAS v2 about a year ago and lost the ability to tweet now playing metadata. After tinkering around, it seems that the v1 script works with the v2 server no problem. Works exactly like before. I figured it should work no problem for v2. I copied all tokens and settings from the v1 script over to v2 easily.

However, for some reason when I view the v2 script in browser it doesn't print the song metadata lie v1. The script fires off a tweet, just without song metadata.

Also, it would be nice to include provisions for other streaming urls as well. (multiple sids)
Example: xxx.xxx.xxx.xx:port/sid=1

**Comment by rackgaming** [comment]
It is possible for multiple streams but you must use the adminview mode

**Comment by rackgaming** [comment]
http://forums.shoutcast.com/showthread.php?t=283241

**Comment by kbysfm** [comment]
thanks @rackgaming got it working.

**Comment by dlnetworks** [comment]
I have updated the code as well. added config option so you can specify a stream id and dressed up the preview output when viewing in a browser.

if you'd like to support more than a single stream/station to tweet to the sane twitter account, simply duplicate the Shoutcast or icecast php file and change the stream details. you can rename the php files to station1.php station2.php, for example.

**Comment by kbysfm** [comment]
Thanks @dlnetworks
