### ISSUE TITLE
Name of the artist not says with icecast

### ISSUE THREAD

**Issue by TuxNuX** [dlnetworks/twittercast#11]
The icecast.php module does not say the name of the artist, it just says the title of the song
I repaired this
 Just need to add variable "$artist_song "

`// add more variables here to get more info from XML
global $listeners;
**global $artist_song;**
global $current_song;

if ($curTag == "^ICESTATS^SOURCE^LISTENERS") {
$listeners = $data;
}

**if ($curTag == "^ICESTATS^SOURCE^ARTIST") {
$artist_song = $data;
}**

if ($curTag == "^ICESTATS^SOURCE^TITLE") {
$current_song = $data;
}}

// control for parsing xml data
$xml_parser = xml_parser_create();
xml_set_element_handler($xml_parser, "startElement", "endElement");
xml_set_character_data_handler($xml_parser, "characterData");
xml_parse($xml_parser, $xml);
xml_parser_free($xml_parser);

// tweet preview
print "$current_song";
**print "$artist_song";**

// post the tweet
$twitterObj->post('/statuses/update.json', array('status' => ''.$current_song.' by **'.$artist_song.'** - '.$listeners.' Listeners - #music #NowPlaying on http://mywebradion.com'));
?>
`

**Comment by dlnetworks** [comment]
added, ty
