### ISSUE TITLE
No $current_track visible after I changed to my new SSL Icecast stream 

### ISSUE THREAD

**Issue by ghost** [dlnetworks/twittercast#12]
I use Twittercast since 2016 with a Icecast stream and everything was working great. Last week I changed to a SSL Icecast stream. After changing the logindata in icecast.php the $current_track wasn't visible anymore, which means, empty nowplaying data in Twitter. Does anybody recognize this problem and knows how to solve the problem?

**Comment by dlnetworks** [comment]
did you change the url from http to https?

`curl_setopt($mysession, CURLOPT_URL, "http://$server/admin/stats.xml?mount=$mount");`

to

`curl_setopt($mysession, CURLOPT_URL, "https://$server/admin/stats.xml?mount=$mount");`

is there anything in the httpd or php error logs?

**Comment by ghost** [comment]
No not yet....
That will be the answer to my question I guess...

Greetz,
Bert

Op 5 feb. 2018 om 09:39 heeft DL Networks <notifications@github.com> het volgende geschreven:

did you change the url from http to https?

curl_setopt($mysession, CURLOPT_URL, "http://$server/admin/stats.xml?mount=$mount");

to

curl_setopt($mysession, CURLOPT_URL, "https://$server/admin/stats.xml?mount=$mount");
