### ISSUE TITLE
IceCast.php does not work

### ISSUE THREAD

**Issue by rackgaming** [dlnetworks/twittercast#2]
Icecast.PHP needs fixing, is there any possible way you can fix the icecast page? It outputs nothing but a dash.

**Comment by dlnetworks** [comment]
what is the stream address of your icecast server, including stream mountpoint?
please also provide your icecast.php.

**Comment by rackgaming** [comment]
<?php
include 'EpiCurl.php';
include 'EpiOAuth.php';
include 'EpiTwitter.php';
#Consumer key token
$consumer_key = 'ihWKrPIeMStXlqZPkfYZYokOE';

#Consumer secret token
$consumer_secret = '9vl7nARSKo9k0kZCpCJFNeOpQLvqCNwkb980eu0cuJyxnKLIM8';

#Access Token
$token = '1890490254-IHdR2KPoWvuOPM4vAXsMuQi36Th2oBAAR9GPUw4';

#Access Token Secret 
$secret= 'D5aTU9KRN7FqXnDD3BEmhUVdZLEj1tqQFS1LPoIJZvtEI';

$twitterObj = new EpiTwitter($consumer_key, $consumer_secret, $token, $secret);
$twitterObjUnAuth = new EpiTwitter($consumer_key, $consumer_secret);
 
$SERVER = 'http://ca2.radioboss.fm:8175'; // url to icecast server and port
$STATS_FILE = '/status.xsl'; // path to status.xsl and mountpoint
// END CONFIGURATION
//create a new curl resource 
$ch = curl_init(); 
//set url 
curl_setopt($ch,CURLOPT_URL,$SERVER.$STATS_FILE); 
//return as a string 
curl_setopt($ch,CURLOPT_RETURNTRANSFER,1); 
//$output = our stauts.xsl file 
$output = curl_exec($ch); 
//close curl resource to free up system resources 
curl_close($ch); 
//build array to store our radio stats for later use 
$radio_info = array(); 
$radio_info['server'] = $SERVER; 
$radio_info['title'] = ''; 
$radio_info['description'] = ''; 
$radio_info['content_type'] = ''; 
$radio_info['mount_start'] = ''; 
$radio_info['bit_rate'] = ''; 
$radio_info['listeners'] = ''; 
$radio_info['most_listeners'] = ''; 
$radio_info['genre'] = ''; 
$radio_info['url'] = ''; 
$radio_info['now_playing'] = array(); 
$radio_info['now_playing']['song'] = ''; 
$radio_info['now_playing']['track'] = ''; 
//loop through $ouput and sort into our different arrays 
$temp_array = array(); 
$search_for = "<td\s[^>]*class=\"streamstats\">(.*)<\/td>"; 
$search_td = array('<td class="streamstats">','</td>'); 
if(preg_match_all("/$search_for/siU",$output,$matches)) { 
   foreach($matches[0] as $match) { 
      $to_push = str_replace($search_td,'',$match); 
      $to_push = trim($to_push); 
      array_push($temp_array,$to_push); 
   } 
} 
//sort our temp array into our ral array 
$radio_info['title'] = $temp_array[0]; 
$radio_info['description'] = $temp_array[1]; 
$radio_info['content_type'] = $temp_array[2]; 
$radio_info['mount_start'] = $temp_array[3]; 
$radio_info['bit_rate'] = $temp_array[4]; 
$radio_info['listeners'] = $temp_array[5]; 
$radio_info['most_listeners'] = $temp_array[6]; 
$radio_info['genre'] = $temp_array[7]; 
$radio_info['url'] = $temp_array[8]; 
$x = explode(" - ",$temp_array[9]); 
$radio_info['now_playing']['artist'] = $x[0]; 
$radio_info['now_playing']['track'] = $x[1]; 
?>

<?php foreach($radio_info as $title => $data) { switch($title) { case 'now_playing' : ?>
<?php print "$data[artist] - $data[track]"; // so you can see what the output looks like
$twitterObj->post('/statuses/update.json', array('status' => $data[artist] .' - ' .$data[track])); 
} } ?>

**Comment by rackgaming** [comment]
Well I switched back to shoutcast but a guy told me that the icecast php script is outdated and does not return any information whatsoever. I did my mountpoint and everything correct but it seems oudated.

**Comment by dlnetworks** [comment]
the page is empty on your shoutcast server for the mount point thats currently active...

http://ca2.radioboss.fm:8175/status.xsl?mount=autodj

**Comment by rackgaming** [comment]
That's because I'm switching it back to shoutcast because the script is broken, even when it was running, it did not produce any metadata.

**Comment by dlnetworks** [comment]
i have updated icecast.php and tested against my own icecast server. everything seems to be in working order again =]
