### ISSUE TITLE
PHP Script with Plain Text URL Support

### ISSUE THREAD

**Issue by LyonelB** [dlnetworks/twittercast#4]
Is it possible to recover the current title from a url (http://www.urban-radio.com/titrage/title_winmedia.html) instead of going through Icecast?

**Comment by dlnetworks** [comment]
`<?php
include 'EpiCurl.php';
include 'EpiOAuth.php';
include 'EpiTwitter.php';

// Consumer key token
$consumer_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxx';

// Consumer secret token
$consumer_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxx';

// Access Token
$token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

// Access Token Secret
$secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

$url = "http://www.domain.com/title.html";

// END CONFIGURATION
$twitterObj = new EpiTwitter($consumer_key, $consumer_secret, $token, $secret);
$twitterObjUnAuth = new EpiTwitter($consumer_key, $consumer_secret);

// opens the url and puts it to a variable for processing
$mysession = curl_init();
curl_setopt($mysession, CURLOPT_URL, "$url");
curl_setopt($mysession, CURLOPT_HEADER, false);
curl_setopt($mysession, CURLOPT_RETURNTRANSFER, true);
curl_setopt($mysession, CURLOPT_POST, false);
curl_setopt($mysession, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($mysession, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
$title = curl_exec($mysession);
curl_close($mysession);

// tweet preview
print "$title";

// post the tweet
$twitterObj->post('/statuses/update.json', array('status' => $title));
?>`

**Comment by LyonelB** [comment]
It's work !

But, i have a problem with accents : "é", "è", "à" ...
How can they be addressed?

When the title contains a letter with an accent, the tweet is truncated:
Example: "Eric Neveux - Liberation"
-> Tweet: "ration"

**Comment by dlnetworks** [comment]
you can try adding

`$title = rawurlencode('$title');`

above the tweet preview

**Comment by LyonelB** [comment]
It's work fr "é" -> https://twitter.com/GraffitiNowPlay/status/792988733884731392
But not for "â" -> https://twitter.com/GraffitiNowPlay/status/792992255556587520

**Comment by dlnetworks** [comment]
This script was hacked together with code from various sources. Never messed with any language/character stuff to make it work. But I'll google a bit.
