### ISSUE TITLE
Missing required parameter: status.

### ISSUE THREAD

**Issue by crewits** [dlnetworks/twittercast#5]
What could be the cause of this error?

Fatal error: Uncaught exception 'EpiTwitterForbiddenException' with message '{"errors":[{"code":170,"message":"Missing required parameter: status."}]}' in /home/site/public_html/app/twcast/EpiTwitter.php:265

**Comment by dlnetworks** [comment]
Sounds like your trying to tweet an empty status. Is the script getting the title from the server?

-DL

**Comment by crewits** [comment]
works now thank you
