### ISSUE TITLE
Exempt some song titles?

### ISSUE THREAD

**Issue by musiclandUSA** [dlnetworks/twittercast#7]
When we run ad overlays I'd prefer it not to tweet those.  ADWTAG is what the title says.

**Comment by dlnetworks** [comment]
in the configuration section at the top you can add

`$adtag = "ADWTAG";`

then at the bottom find the line:

`$twitterObj->post('/statuses/update.json', array('status' => $current_song));`

and replace it with this

`$adcheck = strpos($current_song,$adtag);`
`if($adcheck === false) {`
`$twitterObj->post('/statuses/update.json', array('status' => $current_song));`
`}`

**Comment by musiclandUSA** [comment]
Thanks!  The variable for current song in the script I pulled is $song[1] though.

Would that catch all ADWTAG instances?  We have 90 and 30 and 60, etc.

Be Right Back! - ADWTAG_30000
Be Right Back! - ADWTAG_XXXXX basically

is the exact title.

**Comment by dlnetworks** [comment]
yes the string ADWTAG can appear anywhere in the title, so it checks if its there... if its NOT there, it will post. if it IS there, it will not post.

you can just replace any instance of $current_song with $song[1]
