### ISSUE TITLE
Commas in title result in truncation of the tweet

### ISSUE THREAD

**Issue by musiclandUSA** [dlnetworks/twittercast#9]
Commas in title result in truncation of the song title portion of the tweet

**Comment by TuxNuX** [comment]
I have the same problem
but with accented characters
I'm french and there is a lot accented characters

**Marée Noire by Bézèd'h** 
be in the tweet
**e Noire by d'h**

on icecast server is good no probleme

**Comment by dlnetworks** [comment]
this is due to the script using commas as the delimiter for separating the values from shoutcasts 7.html stats output.

i am in the middle of merging the shoutcast and icecast files into a single script which will use xml based stats output which should resolve this problem. stay tuned.

**Comment by sangset** [comment]
Problem : (') = &apos , (&) = &amp

Title On Shoutcast : Svetlanas - Let's Get Drunk
Result On Tweet : Svetlanas - Let&apos ;s Get Drunk

Title On Shoutcast : Ray & Green - Love Is
Result On Tweet : Ray &amp ; Green - Love Is

please update again....

**Comment by dlnetworks** [comment]
updated and tested. results below.

![screen shot 2018-06-19 at 4 19 06 462am](https://user-images.githubusercontent.com/5649428/41594668-f2e243b6-7378-11e8-8618-15c6cb695a6c.png)

**Comment by dlnetworks** [comment]
shoutcast.php now uses XML based stats

**Comment by sistematico** [comment]
Sorry for reopening, but same issue here with icecast.
